/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: ["./src/**/*.{astro,html,js,jsx,md,mdx,svelte,ts,tsx,vue}"],
  theme: {
    extend: {
      colors: {
        "surface": "#fdf9f0",
        "on-surface": "#1d1c17",
        "on-primary-fixed": "#002020",
        "surface-container": "#f2ede5",
        "tertiary-container": "#4a60ff",
        "tertiary": "#1839fe",
        "inverse-primary": "#76d6d5",
        "secondary": "#6a5f00",
        "primary-fixed": "#93f2f2",
        "on-tertiary-fixed-variant": "#0026d6",
        "error": "#ba1a1a",
        "on-secondary-container": "#6f6300",
        "surface-bright": "#fdf9f0",
        "on-secondary-fixed": "#201c00",
        "tertiary-fixed-dim": "#bcc2ff",
        "surface-variant": "#e6e2da",
        "primary-fixed-dim": "#76d6d5",
        "surface-container-low": "#f8f3eb",
        "on-error": "#ffffff",
        "outline": "#6e7979",
        "secondary-fixed-dim": "#dec800",
        "inverse-on-surface": "#f5f0e8",
        "on-secondary": "#ffffff",
        "primary-container": "#008080",
        "surface-container-highest": "#e6e2da",
        "on-background": "#1d1c17",
        "error-container": "#ffdad6",
        "on-primary": "#ffffff",
        "outline-variant": "#bdc9c8",
        "surface-dim": "#dedad1",
        "tertiary-fixed": "#dfe0ff",
        "surface-container-high": "#ece8df",
        "on-tertiary": "#ffffff",
        "primary": "#006565",
        "on-tertiary-container": "#fbf8ff",
        "surface-tint": "#006a6a",
        "secondary-fixed": "#fde400",
        "surface-container-lowest": "#ffffff",
        "on-tertiary-fixed": "#000c62",
        "secondary-container": "#fae100",
        "inverse-surface": "#32302b",
        "on-secondary-fixed-variant": "#504700",
        "on-error-container": "#93000a",
        "on-primary-container": "#e3fffe",
        "on-surface-variant": "#3e4949",
        "background": "#fdf9f0",
        "on-primary-fixed-variant": "#004f4f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      fontFamily: {
        "display": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Plus Jakarta Sans", "sans-serif"],
        "window-title": ["Plus Jakarta Sans", "sans-serif"],
        "code-lg": ["JetBrains Mono", "monospace"],
        "code-sm": ["JetBrains Mono", "monospace"],
        "label-mono": ["JetBrains Mono", "monospace"],
        "metric-counter": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "body-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "code-lg": ["14px", { lineHeight: "22px", fontWeight: "500" }],
        "label-mono": ["11px", { lineHeight: "14px", letterSpacing: "0.05em", fontWeight: "700" }],
        "code-sm": ["12px", { lineHeight: "18px", fontWeight: "500" }],
        "metric-counter": ["28px", { lineHeight: "32px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "700" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "display": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "headline-sm": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "window-title": ["13px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "700" }],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
